#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import gzip
import json
import os
from concurrent.futures import ThreadPoolExecutor, as_completed

import numpy as np


def parse_args():
    p = argparse.ArgumentParser(
        description=(
            "Filter fragment.tsv(.gz) by a compact tissue mask (方案B). "
            "Mask is stored as a compact grid at mask-bin resolution; filtering is done by integer-aligned mapping."
        )
    )
    p.add_argument("--fragments", required=True, help="Input fragment file (.tsv or .tsv.gz)")
    p.add_argument(
        "--fragment-bin",
        type=int,
        required=True,
        help="Bin size of the input fragments (e.g. 1/20/100). Used for sanity; mapping uses coordinates in the same base unit.",
    )
    p.add_argument("--mask", required=True, help="Mask tif generated by stereoatac_tissuecut_v1.1.py")
    p.add_argument("--mask-bin", type=int, default=20, help="Bin size of the mask (default: 20)")
    p.add_argument(
        "--mask-summary",
        default="",
        help="Path to summary.json for the mask bin directory. If empty, will try <mask_dir>/summary.json",
    )
    p.add_argument(
        "--output",
        default="",
        help="Output tissuecut fragments (.tsv.gz). Default: <fragments_basename>.tissuecut.tsv.gz in same directory",
    )
    p.add_argument("--chunksize", type=int, default=1_000_000, help="pandas read_csv chunksize (default: 1,000,000)")
    p.add_argument("--workers", type=int, default=4, help="Thread workers for chunk filtering (default: 4)")
    return p.parse_args()


def _open_maybe_gzip(path):
    if path.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, "r", encoding="utf-8")


def _load_mask(mask_path):
    try:
        import tifffile  # type: ignore

        arr = tifffile.imread(mask_path)
    except Exception:
        from PIL import Image  # type: ignore

        arr = np.array(Image.open(mask_path))

    if arr.ndim != 2:
        raise ValueError(f"Mask must be 2D. Got shape={arr.shape}")

    # Accept 0/1 or 0/255
    if arr.max() > 1:
        arr = (arr > 0).astype(np.uint8)
    else:
        arr = arr.astype(np.uint8)
    return arr


def _load_summary(summary_path, mask_bin):
    with open(summary_path, "r", encoding="utf-8") as f:
        summ = json.load(f)

    # summary.json is written by stereoatac_tissuecut_v1.1.py/save_outputs()
    minx = int(summ["grid_origin_minx"])
    miny = int(summ["grid_origin_miny"])
    bin_size = int(summ["bin_size"])
    if bin_size != int(mask_bin):
        raise ValueError(f"mask-bin mismatch: summary bin_size={bin_size} but --mask-bin={mask_bin}")
    return minx, miny


def _filter_chunk(df, mask_arr, mask_bin, minx, miny):
    # df columns: chrom,start,end,xy,pcr_dup
    coords = df["xy"].str.extract(r"(\d+)[_](\d+)")
    good = ~coords.isna().any(axis=1)
    if not bool(good.any()):
        return None

    x = coords.loc[good, 0].astype("int64")
    y = coords.loc[good, 1].astype("int64")

    ax = ((x // mask_bin) * mask_bin).to_numpy(dtype=np.int64)
    ay = ((y // mask_bin) * mask_bin).to_numpy(dtype=np.int64)

    gx = ((ax - minx) // mask_bin).astype(np.int64)
    gy = ((ay - miny) // mask_bin).astype(np.int64)

    inside = (
        (gx >= 0)
        & (gy >= 0)
        & (gx < mask_arr.shape[1])
        & (gy < mask_arr.shape[0])
    )
    if inside.sum() == 0:
        return None

    gxv = gx[inside]
    gyv = gy[inside]

    keep = mask_arr[gyv, gxv] > 0
    if keep.sum() == 0:
        return None

    # Map back to df row indices
    idx_good = np.flatnonzero(good.to_numpy())
    #idx_inside = idx_good[inside.to_numpy()]
    idx_inside = idx_good[inside]
    idx_keep = idx_inside[keep]

    return df.iloc[idx_keep]


def main():
    args = parse_args()

    if not args.mask_summary:
        args.mask_summary = os.path.join(os.path.dirname(args.mask), "summary.json")

    if not os.path.exists(args.mask_summary):
        raise FileNotFoundError(f"mask summary.json not found: {args.mask_summary}")

    if not args.output:
        base = os.path.basename(args.fragments)
        if base.endswith(".gz"):
            base = base[:-3]
        if base.endswith(".tsv"):
            base = base[:-4]
        args.output = os.path.join(os.path.dirname(args.fragments), f"{base}.tissuecut.tsv.gz")

    mask_arr = _load_mask(args.mask)
    minx, miny = _load_summary(args.mask_summary, args.mask_bin)

    try:
        import pandas as pd
    except Exception as e:
        raise RuntimeError(f"pandas is required. Import failed: {e}")

    compression = "gzip" if args.fragments.endswith(".gz") else None

    # Read full columns to preserve original lines.
    col_names = ["chrom", "start", "end", "xy", "pcr_dup"]

    # Threaded pipeline: parse/filter chunks in threads, write in main thread.
    max_inflight = max(1, int(args.workers) * 2)

    with gzip.open(args.output, "wt", encoding="utf-8") as fo, ThreadPoolExecutor(max_workers=args.workers) as ex:
        inflight = []
        for chunk in pd.read_csv(
            args.fragments,
            sep="\t",
            header=None,
            names=col_names,
            dtype={"chrom": "string", "start": "int64", "end": "int64", "xy": "string", "pcr_dup": "float32"},
            engine="c",
            compression=compression,
            chunksize=int(args.chunksize),
        ):
            fut = ex.submit(_filter_chunk, chunk, mask_arr, int(args.mask_bin), int(minx), int(miny))
            inflight.append(fut)

            if len(inflight) >= max_inflight:
                done = inflight.pop(0)
                out_df = done.result()
                if out_df is not None and out_df.shape[0] > 0:
                    out_df.to_csv(fo, sep="\t", header=False, index=False)

        # drain
        for fut in inflight:
            out_df = fut.result()
            if out_df is not None and out_df.shape[0] > 0:
                out_df.to_csv(fo, sep="\t", header=False, index=False)

    print(args.output)


if __name__ == "__main__":
    main()
